### ISSUE TITLE
Also for SQLRPGLE?

### ISSUE THREAD

**Issue by RandleBR** [NielsLiisberg/RPG-for-VSCode#2]
Is there a way to also include 'SQLRPGLE' for syntax highlighting with the same extension?

**Comment by NielsLiisberg** [comment]
It is already in the plugin, however Vscode will not see the extension in this version  ..

I'll fix it soon..

Best regards

Niels Liisberg

Chief Software Architect

System & Method

Håndværkersvinget 8
DK-2970 Hørsholm
Phone: +45 70 20 30 10

Fax: +45 70 20 30 11
Direct: +45 45 166 135
Mobile: +45 31 158 861
E-mail: nli@system-method.com
Web: www.system-method.com and www.Icebreak.org

“Everything should be made as simple as possible, but not simpler.”
— Albert Einstein

**Comment by NielsLiisberg** [comment]
Ready !!

Just reload the extension - now version 1.1
