### ISSUE TITLE
Future of RPG-for-VSCdoe

### ISSUE THREAD

**Issue by ghost** [NielsLiisberg/RPG-for-VSCode#7]
Hi Niels,
I appreciate VSCode very much. Great idea to integrate RPGLE, but i see no more improvements of you. Did you stop the project? I see Liams  ILEditor2 as commercial project, however in my opinion too expensive. Normally i use RDi (horrible at remote works) but if a slighter solution is available - give it to me.

**Comment by NielsLiisberg** [comment]
Hello Karl-Fritz;

I am actually working on something great - the IBMiFS that allows you to work directly on the IBM i source file system ( QRPGLESRC etc.) However this is actually a rather complicated task. One of the reasons is that my client don't want to let go the source change date, so I have to implement crazy algoritmes to facilitate that - Here is the source for that:

https://gist.github.com/NielsLiisberg/7881bd320eb281b566dab44c7ceeb50e

Also the dialogs in workspaces is not easy to map the way the sourcefiles works on IBM i - I am implementing the filters as you know from RDi, but it does not works naturally from vsCode.. 

Also the "build" process is not the same on IBM i as with i.e. make, and I doubt I can convince IBM i guys to adopt the gmake way of thinking, so I have to implement "option 14" and "Option 15"

If you however are ready to look into the gmake, then take a look at this:

https://github.com/NielsLiisberg/RPG-vsCode-Getting-Started
 
So still lot of work to do - but stay tuned !!  

Thank you for you feedback

**Comment by NielsLiisberg** [comment]
Hello Karl-Fritz. 

Now it is updated and have cool snippets... Some progress :)
